services:
  mem0_store:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - mem0_storage:/mem0/storage
  openmemory-mcp:
    image: mem0/openmemory-mcp:latest
    env_file:
      - .env
    environment:
      - QDRANT_HOST=mem0_store
      - QDRANT_PORT=6333
    ports:
      - "8765:8765"
    depends_on:
      - mem0_store
  openmemory-ui:
    image: mem0/openmemory-ui:latest
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8765
    ports:
      - "3000:3000"

volumes:
  mem0_storage:
